# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/montel-ig/docker-machine-driver-upcloud
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build the driver
          command: make build
